#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://about.travis-ci.org/docs/user/languages/php for more hints
#
language: php

# use container based infrastructure (no sudo possible)
sudo: false

cache:
  directory:
    - $HOME/.composer/cache/files

php: [5.5, 5.6, 7, hhvm]

before_install:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - phpunit --configuration ./tests/phpunit.xml.dist
  # tests
  # require "1.9.8"
  #- cd "$TRAVIS_BUILD_DIR/tests/example-v1.9.8" && composer install -vvv --profile
  #- ls -ashF bin
  #- bin/phantomjs -v
  #- cd $TRAVIS_BUILD_DIR
  # require "dev-master"
  - cd "$TRAVIS_BUILD_DIR/tests/example-latest-version" && composer install -vvv --profile
  - ls -ashF bin
  - bin/phantomjs -v
  # require "2.0.0" and lower version automatically to "1.9.8"
  - cd "$TRAVIS_BUILD_DIR/tests/example-v2.0.0-v1.9.8" && composer install -vvv --profile
  - ls -ashF bin
  - bin/phantomjs -v

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#koch"
    use_notice: true

# reduce commit history of git checkout
git:
  depth: 5
