#
# .travis.yml - configuration file for the travis continuous integration service
#
# see https://docs.travis-ci.com/user/languages/php/ for more hints
#
language: php

# use container based infrastructure (no sudo possible)
sudo: false

cache:
  directory:
    - $HOME/.composer/cache/files

php: [7.2, 7.4]

before_install:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --configuration ./tests/phpunit.xml.dist
  # tests
  # Using Composer v1
  # require "dev-master" -> v2.1.1 (hardcoded fallback)
  - cd "$TRAVIS_BUILD_DIR/tests/example-latest-version" && composer install -vvv --profile
  - ls -ashF bin
  - bin/phantomjs -v
  # Using Composer 2.0-dev snapshot
  - composer self-update --snapshot
  - composer --version
  # require "dev-master" -> v2.1.1 (composer.json's extra section)
  - cd "$TRAVIS_BUILD_DIR/tests/example-extra-version" && composer install -vvv --profile
  - ls -ashF bin
  - bin/phantomjs -v
  # Reminder:
  # if you define version "2.0.0" in composer.json's extra section,
  # it should fetch v1.9.8 via retry/auto-lowering.

# reduce commit history of git checkout
git:
  depth: 5
